/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2Q1u9B8Ugbj
 */
import Link from "next/link"
import FooterComponent from "../ui/footer-component"
import HeaderComponent from "../ui/header-component"

export function FeatureComponent() {
  return (
    <div className="flex flex-col min-h-[100vh]">
      <main className="flex-1">
        <section className="w-full min-h-screen py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                  Explore Our Features
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                  Discover how our platform can help you grow your online presence and engage with your audience.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full min-h-screen py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Key Features
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Empower Your Online Presence</h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Our platform offers a variety of features to help you engage with your audience and grow your online
                  presence.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">Customizable Lectures</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Create and customize your own lectures to suit your teaching style and audience.
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">Interactive Q&A</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Engage with your audience through interactive Q&A sessions during your lectures.
                  </p>
                </div>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">Audience Engagement Tools</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Utilize our audience engagement tools to keep your audience active and interested.
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">Advanced Analytics</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Gain insights into your audiences behavior with our advanced analytics tools.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}